# Generated by Django 5.2.13 on 2026-06-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status_alter_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('price_zone', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.eventseat'),
        ),
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(default=6)),
                ('cols', models.PositiveIntegerField(default=7)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Metadata: {"price_zones": {"vip": [rows], "standard": [rows]}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_map', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'seat maps',
            },
        ),
        migrations.AddField(
            model_name='eventseat',
            name='seat_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.seatmap'),
        ),
        migrations.AddIndex(
            model_name='eventseat',
            index=models.Index(fields=['seat_map', 'is_available'], name='events_even_seat_ma_f7d023_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventseat',
            unique_together={('seat_map', 'row', 'col')},
        ),
    ]
