# Generated by Django 5.2.15 on 2026-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventseat_registration_seat_seatmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='seat_held_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
