# Generated by Django 5.2.15 on 2026-06-05 09:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_seat_held_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
