# Generated by Django 5.2.15 on 2026-06-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_notification_favorite_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Case-insensitive code attendees type at checkout', max_length=50)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='20 = 20% (percent) or $20 (fixed)', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.promocode'),
        ),
    ]
