# Generated by Django 5.2.15 on 2026-06-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventquestion_questionanswer_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free'), ('donation', 'Donation (pay what you want)')], default='paid', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('min_per_order', models.PositiveIntegerField(default=1)),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['order', 'price', 'id'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.tickettype'),
        ),
    ]
