# Generated by Django 5.2.15 on 2026-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_registration_donation_amount_tickettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='fees_passed_to_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform/booking fee as a %', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. 12 for 12% VAT', max_digits=5),
        ),
    ]
