# Generated by Django 5.2.15 on 2026-06-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_affiliate_registration_affiliate_webhook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, help_text="Attendee's reason for the request")),
                ('organizer_note', models.CharField(blank=True, help_text="Organizer's response", max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='events.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
